"""initial_notification

Revision ID: 0958e4fc69c2
Revises:
Create Date: 2026-05-24 02:23:48.667226

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0958e4fc69c2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Применить изменения схемы.

    :return: None
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification",
        sa.Column("type", sa.Enum("EMAIL", "TELEGRAM", "SMS", name="notificationtypeenum"), nullable=False),
        sa.Column("recipient", sa.VARCHAR(length=320), nullable=False),
        sa.Column("subject", sa.VARCHAR(length=500), nullable=True),
        sa.Column("message", sa.TEXT(), nullable=False),
        sa.Column("channel_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status", sa.Enum("QUEUED", "PENDING", "SENT", "FAILED", name="notificationstatusenum"), nullable=False
        ),
        sa.Column("error_text", sa.VARCHAR(length=500), nullable=True),
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("uid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откатить изменения схемы.

    :return: None
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification")
    # ### end Alembic commands ###
